#cloud-config
write_files:
  - path: /etc/systemd/system/docker-registry.service
    owner: root:root
    permissions: "0644"
    content: |
      [Unit]
      Description=Docker registry service with docker compose
      PartOf=docker.service
      After=docker.service

      [Service]
      Type=oneshot
      RemainAfterExit=true
      WorkingDirectory=/opt/basic-registry/
      ExecStart=/usr/bin/docker-compose up -d --remove-orphans
      ExecStop=/usr/bin/docker-compose down
      ExecStartPost=/usr/bin/timeout 30 sh -c 'while ! ss -H -t -l -n sport = :443 | grep -q "^LISTEN.*:443"; do sleep 1; done'

      [Install]
      WantedBy=multi-user.target  